name: Push to Remote

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git credentials
        run: |
          git config --global user.name "${{ secrets.NW_USER }}"
          git config --global user.password "${{ secrets.NW_PASS }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to Remote with username and password
        run: |
          git remote add milkyway https://$NW_USER:$NW_PASS@git.nekoweb.org/milkyway.git
          git push -f milkyway HEAD:main
        env:
          NW_USER: ${{ secrets.NW_USER }}
          NW_PASS: ${{ secrets.NW_PASS }}
