name: Push to Remote

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git credentials
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global credential.helper '!echo "username=${GIT_USERNAME}"; echo "password=${GIT_PASSWORD}" > $HOME/.git-credentials'
          git remote add milkyway https://git.nekoweb.org/milkyway.git

      - name: Push to Remote
        run: git push milkyway HEAD:main
        env:
          GIT_USERNAME: ${{ secrets.NW_USER }}
          GIT_PASSWORD: ${{ secrets.NW_PASS }}
