name: deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: deploy web page on webserver
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/milkyway.moe/main && git reset --hard && git pull origin main
          host: '45.86.153.175'
          port: 22
          username: github
          password: ${{ secrets.SERVERPASSWD }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
        env:
          CI: true
