name: Push to Remote

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git credentials
        run: |
          git config --global user.name "${{ secrets.NW_USER }}"
          git config --global user.email "${{ secrets.NW_EMAIL }}"
          git config --global credential.helper store
          git remote add milkyway https://git.nekoweb.org/milkyway.git

      - name: Push to Remote with force
        run: git push -f milkyway HEAD:main
